services:
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    image: ollama/ollama:latest
    command: serve && pull llama3
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    container_name: app
    volumes:
      - /app/:/code/app/
    depends_on:
      - ollama